"""chance type - trans_type in Transaction

Revision ID: 6c238a726e68
Revises: e0968766f042
Create Date: 2026-01-23 19:14:31.947443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c238a726e68'
down_revision = 'e0968766f042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trans_type', sa.String(length=20), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('trans_type')

    # ### end Alembic commands ###
